package:
  name: tephrite
  version: "0.1.0a0.dev0"

source:
  - path: "../target"
  - path: "../LICENSE"

build:
  noarch: generic
  include_recipe: False
  script: mkdir -p $PREFIX/lib/mojo && cp $SRC_DIR/$PKG_NAME.mojopkg $PREFIX/lib/mojo

about:
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Build and publish Conda Mojo packages
  description: Build and publish Conda packages from Mojo projects
